# __Homework 2__

In [31]:
import numpy as np
from scipy.stats import binom

## Call Payoff Function
def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)

## Put Payoff Function
def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

In [5]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = 0.8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            delta = Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
            beta = Bt[j, t] = np.exp(-r * h) * (((u * Ct[j + 1, t+1]) - (d * Ct[j, t+ 1]))/(u - d))
            print(f"The beta is: {beta : 0.3f} and the delta is {delta : 0.3f}")
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))
                    
            
    return Ct[0,0]
            

### __Problem 1__
 
Let $S = \$100$, $K = \$105$, $r = 8\%$, $T = 0.5$, and $\delta = 0.0$. Let $u = 1.3$, $d = 0.8$, and $n = 1$.

<br>
  What are the premium, $\Delta$, and $B$ for a European call?
    
  What are the premium, $\Delta$, and $B$ for a European put?
<br>
<br>

In [6]:
S = 100
K = 105
r = 0.08
v = 0.30
q = 0.0
T = 0.5
n = 1

In [7]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f} and the Put Premium is {putPrc : 0.3f}")

The beta is: -38.432 and the delta is  0.500
The beta is:  62.451 and the delta is -0.500
The European Call Premium:  11.568 and the Put Premium is  12.451


### __Problem 2__

Let $S = \$100$, $K = \$95$, $r = 8\%$, $T = 0.5$, and $\delta = 0.0$. Let $u = 1.3$, $d = 0.8$, and $n = 1$.
<br>
 Verify that the price of a European put is $\$7.471$.  
 Suppose you observe a call price of $\$17$. What is the arbitrage?  
 Suppose you observe a call price of $\$15.50$. What is the arbitrage?  
\end{itemize}

In [8]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 0.5
n = 1

In [9]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f} and the Put Premium is {putPrc : 0.3f}")

The beta is: -53.804 and the delta is  0.700
The beta is:  37.471 and the delta is -0.300
The European Call Premium:  16.196 and the Put Premium is  7.471


b) Observe 17 =  The arbitrage would be to short the call of 16.19 of .81 cents  
c. Observe 15.50 = The arbitrage would be to long the call of 16.19 of .69 cents

### __Problem 3__

Let $S = \$100$, $K = \$95$, $\sigma = 30\%$, $r = 8\%$, $T = 1$, and $\delta = 0.0$. Let $u = 1.3$, $d = 0.8$, and $n = 2$.  
  
Construct the binomial tree for a call option. At each node provide the premium, $\Delta$, and $B$.


In [10]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 2

In [11]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = True)
print(f"The European Call Premium: {callPrc : 0.3f}")

The beta is: -91.275 and the delta is  1.000
The beta is: -13.835 and the delta is  0.225
The beta is: -49.127 and the delta is  0.691
[[100. 130. 169.]
 [  0.  80. 104.]
 [  0.   0.  64.]]


[[19.994 38.725 74.   ]
 [ 0.     4.165  9.   ]
 [ 0.     0.     0.   ]]


[[0.691 1.    0.   ]
 [0.    0.225 0.   ]
 [0.    0.    0.   ]]


[[-49.127 -91.275   0.   ]
 [  0.    -13.835   0.   ]
 [  0.      0.      0.   ]]
The European Call Premium:  19.994


### __Problem 4__

Repeat the option price calculation in the previous question for stock prices of $\$80$, $\$90$, $\$110$,
$\$120$, and $\$130$, but now let $n = 3$. Keep everyting else fixed. What happens to the initial option
$\Delta$ as the stock price increases?

In [12]:
S = 80

In [13]:
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f}")

The beta is: -61.798 and the delta is  0.773
The beta is:  0.000 and the delta is  0.000
The beta is: -28.596 and the delta is  0.465
The European Call Premium:  8.608


In [14]:
S = 90
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f}")

The beta is: -87.778 and the delta is  0.976
The beta is:  0.000 and the delta is  0.000
The beta is: -40.618 and the delta is  0.587
The European Call Premium:  12.227


In [15]:
S = 110
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f}")

The beta is: -91.275 and the delta is  1.000
The beta is: -29.823 and the delta is  0.441
The beta is: -57.090 and the delta is  0.777
The European Call Premium:  28.406


In [16]:
S = 120
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f}")

The beta is: -91.275 and the delta is  1.000
The beta is: -45.810 and the delta is  0.621
The beta is: -65.052 and the delta is  0.849
The European Call Premium:  36.819


In [17]:
S = 130
callPrc = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f}")

The beta is: -91.275 and the delta is  1.000
The beta is: -61.798 and the delta is  0.773
The beta is: -73.015 and the delta is  0.910
The European Call Premium:  45.231


Delta increases at a decreasing rate as the spot price increases

### __Problem 5__

Let $S = \$100$, $K = \$95$, $r = 8\%$ (continuously compounded), $\sigma = 30\%$, $\delta = 0$, and $T = 1$ year and $n = 3$.

What is the premium for an American call option? Is there any early exercise?  
 What is the premium for a European call option? Use the computational shortcut with the
 risk-neutral binomial pmf that I showed you in class. Compare the American and European premia.  
 What is the premium for a European put? Does put-call parity hold? (see McDonald Chapter 9). Also use the risk-neutral binomial pmf for this problem.    
What is the premium of the American put? Compare with the European put. If they differ, explain why.

<br>

In [57]:
def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = False):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    ## Arrays to store the spot prices and option values
    Ct = np.empty(nodes)
    St = np.empty(nodes)
    
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
    
    if verbose:
        print(Ct)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            Ct[j] = np.maximum(Ct[j], K - St[j])
            print(Ct)
            
    return Ct[0]

In [58]:
def euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, payoff, verbose = False):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
          
    return Ct[0,0]


In [59]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3

In [61]:
callPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff,  verbose = False)
callPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff,  verbose = False)
putPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)

print(f"The European Call Premium: {callPrcE : 0.3f} The American call is {callPrcE : 0.3f}")
print(f"The European Put Premium: {putPrcE : 0.3f} The American put is {putPrcA : 0.3f}")



[56.64406241 33.8147424   0.          0.        ]
[56.64406241 15.04032855  0.          0.        ]
[56.64406241 15.04032855 20.40351726  0.        ]
[33.14931753 15.04032855 20.40351726  0.        ]
[33.14931753 17.48114202 20.40351726  0.        ]
[23.99012609 17.48114202 20.40351726  0.        ]
[ 0.          0.          3.89933488 30.57157332]
[ 0.          2.06235672  3.89933488 30.57157332]
[ 0.          2.06235672 20.40351726 30.57157332]
[ 1.09077967  2.06235672 20.40351726 30.57157332]
[ 1.09077967 11.7087201  20.40351726 30.57157332]
[ 6.67790123 11.7087201  20.40351726 30.57157332]
The European Call Premium:  18.283 The American call is  18.283
The European Put Premium:  5.979 The American put is  6.678


In [63]:
parity = S - (K * np.exp(-r*T))
parity
parity1 = callPrc - putPrc
parity1

12.30394709326959

#### __Problem 6__

Let $S = \$40$, $K = \$40$, $r = 8\%$ (continuously compounded), $\sigma = 30\%$, $\delta = 0.0$, $T = 0.5$ year,
and $n = 3$.

 Construct the binomial tree for the stock. What are $u$ and $d$?  
 Compute the premia of American and European calls and puts.



In [68]:
S = 40
K = 40
r = 0.08
v = 0.30
q = 0.0
T = 0.5
n = 3
h = T/n

u6 = np.exp((r - q) * h + v * np.sqrt(h))
d6 = np.exp((r - q) * h - v * np.sqrt(h))

In [72]:
callPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff,  verbose = False)
callPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, callPayoff,  verbose = False)
putPrcA = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff,  verbose = False)
putPrcE = euroBinomPricerRecursiveMatrix(S, K, r, v, q, T, n, putPayoff,  verbose = False)

[13.01309727  7.05673217  0.          0.        ]
[13.01309727  3.26869392  0.          0.        ]
[13.01309727  3.26869392  7.84406148  0.        ]
[7.73902974 3.26869392 7.84406148 0.        ]
[7.73902974 5.6208478  7.84406148 0.        ]
[6.52754713 5.6208478  7.84406148 0.        ]
[ 0.          0.          3.16660277 11.16886174]
[ 0.          1.65788424  3.16660277 11.16886174]
[ 0.          1.65788424  7.84406148 11.16886174]
[ 0.86799019  1.65788424  7.84406148 11.16886174]
[ 0.86799019  4.8747172   7.84406148 11.16886174]
[ 2.95422756  4.8747172   7.84406148 11.16886174]


In [74]:
print(f"The u value is {u6 : 0.3f} and the d value is {d6 : 0.3f}")
print(f"The European Call Premium: {callPrcE : 0.3f} The American call is {callPrcE : 0.3f}")
print(f"The European Put Premium: {putPrcE : 0.3f} The American put is {putPrcA : 0.3f}")


The u value is  1.145 and the d value is  0.897
The European Call Premium:  4.377 The American call is  4.377
The European Put Premium:  2.809 The American put is  2.954
